// Code generated by protoc-gen-go. DO NOT EDIT.
// source: darkside.proto

package walletrpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DarksideMetaState struct {
	SaplingActivation    int32    `protobuf:"varint,1,opt,name=saplingActivation,proto3" json:"saplingActivation,omitempty"`
	BranchID             string   `protobuf:"bytes,2,opt,name=branchID,proto3" json:"branchID,omitempty"`
	ChainName            string   `protobuf:"bytes,3,opt,name=chainName,proto3" json:"chainName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DarksideMetaState) Reset()         { *m = DarksideMetaState{} }
func (m *DarksideMetaState) String() string { return proto.CompactTextString(m) }
func (*DarksideMetaState) ProtoMessage()    {}
func (*DarksideMetaState) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ea18aa1b2b1f163, []int{0}
}

func (m *DarksideMetaState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DarksideMetaState.Unmarshal(m, b)
}
func (m *DarksideMetaState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DarksideMetaState.Marshal(b, m, deterministic)
}
func (m *DarksideMetaState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DarksideMetaState.Merge(m, src)
}
func (m *DarksideMetaState) XXX_Size() int {
	return xxx_messageInfo_DarksideMetaState.Size(m)
}
func (m *DarksideMetaState) XXX_DiscardUnknown() {
	xxx_messageInfo_DarksideMetaState.DiscardUnknown(m)
}

var xxx_messageInfo_DarksideMetaState proto.InternalMessageInfo

func (m *DarksideMetaState) GetSaplingActivation() int32 {
	if m != nil {
		return m.SaplingActivation
	}
	return 0
}

func (m *DarksideMetaState) GetBranchID() string {
	if m != nil {
		return m.BranchID
	}
	return ""
}

func (m *DarksideMetaState) GetChainName() string {
	if m != nil {
		return m.ChainName
	}
	return ""
}

// A block is a hex-encoded string.
type DarksideBlock struct {
	Block                string   `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DarksideBlock) Reset()         { *m = DarksideBlock{} }
func (m *DarksideBlock) String() string { return proto.CompactTextString(m) }
func (*DarksideBlock) ProtoMessage()    {}
func (*DarksideBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ea18aa1b2b1f163, []int{1}
}

func (m *DarksideBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DarksideBlock.Unmarshal(m, b)
}
func (m *DarksideBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DarksideBlock.Marshal(b, m, deterministic)
}
func (m *DarksideBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DarksideBlock.Merge(m, src)
}
func (m *DarksideBlock) XXX_Size() int {
	return xxx_messageInfo_DarksideBlock.Size(m)
}
func (m *DarksideBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_DarksideBlock.DiscardUnknown(m)
}

var xxx_messageInfo_DarksideBlock proto.InternalMessageInfo

func (m *DarksideBlock) GetBlock() string {
	if m != nil {
		return m.Block
	}
	return ""
}

// DarksideBlocksURL is typically something like:
// https://raw.githubusercontent.com/zcash-hackworks/darksidewalletd-test-data/master/basic-reorg/before-reorg.txt
type DarksideBlocksURL struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DarksideBlocksURL) Reset()         { *m = DarksideBlocksURL{} }
func (m *DarksideBlocksURL) String() string { return proto.CompactTextString(m) }
func (*DarksideBlocksURL) ProtoMessage()    {}
func (*DarksideBlocksURL) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ea18aa1b2b1f163, []int{2}
}

func (m *DarksideBlocksURL) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DarksideBlocksURL.Unmarshal(m, b)
}
func (m *DarksideBlocksURL) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DarksideBlocksURL.Marshal(b, m, deterministic)
}
func (m *DarksideBlocksURL) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DarksideBlocksURL.Merge(m, src)
}
func (m *DarksideBlocksURL) XXX_Size() int {
	return xxx_messageInfo_DarksideBlocksURL.Size(m)
}
func (m *DarksideBlocksURL) XXX_DiscardUnknown() {
	xxx_messageInfo_DarksideBlocksURL.DiscardUnknown(m)
}

var xxx_messageInfo_DarksideBlocksURL proto.InternalMessageInfo

func (m *DarksideBlocksURL) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

// DarksideTransactionsURL refers to an HTTP source that contains a list
// of hex-encoded transactions, one per line, that are to be associated
// with the given height (fake-mined into the block at that height)
type DarksideTransactionsURL struct {
	Height               int32    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DarksideTransactionsURL) Reset()         { *m = DarksideTransactionsURL{} }
func (m *DarksideTransactionsURL) String() string { return proto.CompactTextString(m) }
func (*DarksideTransactionsURL) ProtoMessage()    {}
func (*DarksideTransactionsURL) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ea18aa1b2b1f163, []int{3}
}

func (m *DarksideTransactionsURL) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DarksideTransactionsURL.Unmarshal(m, b)
}
func (m *DarksideTransactionsURL) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DarksideTransactionsURL.Marshal(b, m, deterministic)
}
func (m *DarksideTransactionsURL) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DarksideTransactionsURL.Merge(m, src)
}
func (m *DarksideTransactionsURL) XXX_Size() int {
	return xxx_messageInfo_DarksideTransactionsURL.Size(m)
}
func (m *DarksideTransactionsURL) XXX_DiscardUnknown() {
	xxx_messageInfo_DarksideTransactionsURL.DiscardUnknown(m)
}

var xxx_messageInfo_DarksideTransactionsURL proto.InternalMessageInfo

func (m *DarksideTransactionsURL) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *DarksideTransactionsURL) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type DarksideHeight struct {
	Height               int32    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DarksideHeight) Reset()         { *m = DarksideHeight{} }
func (m *DarksideHeight) String() string { return proto.CompactTextString(m) }
func (*DarksideHeight) ProtoMessage()    {}
func (*DarksideHeight) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ea18aa1b2b1f163, []int{4}
}

func (m *DarksideHeight) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DarksideHeight.Unmarshal(m, b)
}
func (m *DarksideHeight) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DarksideHeight.Marshal(b, m, deterministic)
}
func (m *DarksideHeight) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DarksideHeight.Merge(m, src)
}
func (m *DarksideHeight) XXX_Size() int {
	return xxx_messageInfo_DarksideHeight.Size(m)
}
func (m *DarksideHeight) XXX_DiscardUnknown() {
	xxx_messageInfo_DarksideHeight.DiscardUnknown(m)
}

var xxx_messageInfo_DarksideHeight proto.InternalMessageInfo

func (m *DarksideHeight) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type DarksideEmptyBlocks struct {
	Height               int32    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Nonce                int32    `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Count                int32    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DarksideEmptyBlocks) Reset()         { *m = DarksideEmptyBlocks{} }
func (m *DarksideEmptyBlocks) String() string { return proto.CompactTextString(m) }
func (*DarksideEmptyBlocks) ProtoMessage()    {}
func (*DarksideEmptyBlocks) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ea18aa1b2b1f163, []int{5}
}

func (m *DarksideEmptyBlocks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DarksideEmptyBlocks.Unmarshal(m, b)
}
func (m *DarksideEmptyBlocks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DarksideEmptyBlocks.Marshal(b, m, deterministic)
}
func (m *DarksideEmptyBlocks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DarksideEmptyBlocks.Merge(m, src)
}
func (m *DarksideEmptyBlocks) XXX_Size() int {
	return xxx_messageInfo_DarksideEmptyBlocks.Size(m)
}
func (m *DarksideEmptyBlocks) XXX_DiscardUnknown() {
	xxx_messageInfo_DarksideEmptyBlocks.DiscardUnknown(m)
}

var xxx_messageInfo_DarksideEmptyBlocks proto.InternalMessageInfo

func (m *DarksideEmptyBlocks) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *DarksideEmptyBlocks) GetNonce() int32 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *DarksideEmptyBlocks) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*DarksideMetaState)(nil), "cash.z.wallet.sdk.rpc.DarksideMetaState")
	proto.RegisterType((*DarksideBlock)(nil), "cash.z.wallet.sdk.rpc.DarksideBlock")
	proto.RegisterType((*DarksideBlocksURL)(nil), "cash.z.wallet.sdk.rpc.DarksideBlocksURL")
	proto.RegisterType((*DarksideTransactionsURL)(nil), "cash.z.wallet.sdk.rpc.DarksideTransactionsURL")
	proto.RegisterType((*DarksideHeight)(nil), "cash.z.wallet.sdk.rpc.DarksideHeight")
	proto.RegisterType((*DarksideEmptyBlocks)(nil), "cash.z.wallet.sdk.rpc.DarksideEmptyBlocks")
}

func init() { proto.RegisterFile("darkside.proto", fileDescriptor_5ea18aa1b2b1f163) }

var fileDescriptor_5ea18aa1b2b1f163 = []byte{
	// 478 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xed, 0x6e, 0xd3, 0x30,
	0x14, 0x6d, 0x3a, 0xa5, 0xa2, 0x77, 0xda, 0xb4, 0x9a, 0xb1, 0x95, 0xb2, 0x1f, 0x53, 0x44, 0xa5,
	0x08, 0xa1, 0x80, 0xe0, 0x09, 0xb6, 0x0e, 0xc1, 0x24, 0x40, 0x22, 0x1d, 0x42, 0x83, 0x1f, 0xe8,
	0xd6, 0xb1, 0x9a, 0xa8, 0x89, 0x13, 0x39, 0xde, 0xa6, 0xc1, 0x9b, 0xf1, 0x28, 0x3c, 0x0d, 0x8a,
	0xed, 0xac, 0x29, 0x25, 0xb8, 0xda, 0xaf, 0xf8, 0xda, 0xe7, 0x9e, 0x73, 0xee, 0x87, 0x02, 0xbb,
	0x11, 0x8a, 0x45, 0x99, 0x44, 0x2c, 0x28, 0x44, 0x2e, 0x73, 0xf2, 0x88, 0x62, 0x19, 0x07, 0x3f,
	0x82, 0x1b, 0x4c, 0x53, 0x26, 0x83, 0x32, 0x5a, 0x04, 0xa2, 0xa0, 0xa3, 0x9d, 0x92, 0x89, 0xeb,
	0x84, 0x1a, 0x94, 0xf7, 0x13, 0x06, 0x67, 0x26, 0xef, 0x03, 0x93, 0x38, 0x95, 0x28, 0x19, 0x79,
	0x0e, 0x83, 0x12, 0x8b, 0x34, 0xe1, 0xf3, 0x13, 0x2a, 0x93, 0x6b, 0x94, 0x49, 0xce, 0x87, 0xce,
	0xb1, 0xe3, 0xbb, 0xe1, 0xfa, 0x03, 0x19, 0xc1, 0x83, 0x99, 0x40, 0x4e, 0xe3, 0xf3, 0xb3, 0x61,
	0xf7, 0xd8, 0xf1, 0xfb, 0xe1, 0x5d, 0x4c, 0x8e, 0xa0, 0x4f, 0x63, 0x4c, 0xf8, 0x47, 0xcc, 0xd8,
	0x70, 0x4b, 0x3d, 0x2e, 0x2f, 0xbc, 0x31, 0xec, 0xd4, 0xe2, 0xa7, 0x69, 0x4e, 0x17, 0x64, 0x1f,
	0xdc, 0x59, 0x75, 0x50, 0x62, 0xfd, 0x50, 0x07, 0xde, 0x78, 0xe9, 0x51, 0xc1, 0xca, 0xcf, 0xe1,
	0x7b, 0xb2, 0x07, 0x5b, 0x57, 0x22, 0x35, 0xc0, 0xea, 0xe8, 0x4d, 0xe0, 0xb0, 0x86, 0x5d, 0x08,
	0xe4, 0x25, 0xd2, 0xca, 0x9e, 0x02, 0x1f, 0x40, 0x2f, 0x66, 0xc9, 0x3c, 0x96, 0xa6, 0x0a, 0x13,
	0xd5, 0x24, 0xdd, 0x25, 0x89, 0x0f, 0xbb, 0x35, 0xc9, 0x3b, 0x8d, 0x69, 0xc9, 0xf5, 0x2e, 0xe1,
	0x61, 0x8d, 0x7c, 0x93, 0x15, 0xf2, 0x56, 0x5b, 0x6b, 0x95, 0xda, 0x07, 0x97, 0xe7, 0x9c, 0x32,
	0x25, 0xe6, 0x86, 0x3a, 0xa8, 0x6e, 0x69, 0x7e, 0xc5, 0xa5, 0xea, 0x8d, 0x1b, 0xea, 0xe0, 0xd5,
	0xef, 0x1e, 0xec, 0xd5, 0xdc, 0x53, 0x29, 0x18, 0x66, 0x4c, 0x90, 0x4f, 0xe0, 0x86, 0xac, 0x64,
	0x92, 0xf8, 0xc1, 0x3f, 0x27, 0x1b, 0xac, 0xcd, 0x71, 0x74, 0xd4, 0x82, 0x54, 0x7e, 0xbd, 0x0e,
	0xf9, 0x06, 0x83, 0xa9, 0xc4, 0xb9, 0xe9, 0xaa, 0x56, 0x22, 0x4f, 0x2d, 0xf4, 0x0a, 0x6c, 0xa3,
	0xf6, 0x1d, 0xf2, 0x05, 0xb6, 0x1b, 0xe4, 0x56, 0xd7, 0x77, 0x93, 0xb5, 0xba, 0xfe, 0xbe, 0xe2,
	0x7a, 0x22, 0x58, 0xb5, 0xb2, 0xcf, 0x2c, 0xf4, 0x8d, 0x11, 0x59, 0x05, 0x66, 0x70, 0xa8, 0x04,
	0x9a, 0x5b, 0x64, 0x9a, 0x33, 0x6e, 0x49, 0x0d, 0xf1, 0xa6, 0x81, 0xde, 0xa0, 0x3b, 0xd4, 0x14,
	0xd1, 0xd4, 0x20, 0x81, 0xa5, 0x88, 0xbf, 0xd6, 0xda, 0x5a, 0xc8, 0x05, 0x6c, 0x9f, 0x14, 0x45,
	0x7a, 0xab, 0x94, 0xa2, 0x56, 0xf3, 0xab, 0x0b, 0xbf, 0x49, 0x7b, 0xde, 0x32, 0x79, 0xce, 0x69,
	0x9e, 0x25, 0x7c, 0xbe, 0x52, 0xc0, 0x7f, 0x53, 0x47, 0x9b, 0x35, 0xcf, 0xeb, 0xbc, 0x74, 0xc8,
	0x25, 0x3c, 0x9e, 0xa4, 0x0c, 0xc5, 0x3d, 0x54, 0x2c, 0xf6, 0x4f, 0x9f, 0x7c, 0x3d, 0x48, 0xab,
	0x3a, 0xf5, 0x73, 0xf4, 0x42, 0x7f, 0x45, 0x41, 0x7f, 0x75, 0x3b, 0xb3, 0x9e, 0xfa, 0x2b, 0xbe,
	0xfe, 0x13, 0x00, 0x00, 0xff, 0xff, 0x9d, 0xe7, 0x29, 0xf3, 0x4d, 0x05, 0x00, 0x00,
}
